apiVersion: v2
name: github-actions-cache-server
description: Self-hosted GitHub Actions cache server
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - github-actions
  - cache
  - ci
annotations:
  category: CI/CD
  licenses: MIT
