apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghacs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "ghacs.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: cache
      protocol: TCP
      name: cache
  selector: {{- include "ghacs.selectorLabels" . | nindent 4 }}
